// tslint:disable
/**
 * of Turnkey API
 * Documentation for Turnkey API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined, OperationOpts, RawAjaxResponse } from '../runtime';
import {
    AuthDto,
    GenericError,
    Token,
} from '../models';

export interface SignInRequest {
    body: AuthDto;
}

/**
 * no description
 */
export class AuthApi extends BaseAPI {

    /**
     * create a new auth
     */
    signIn({ body }: SignInRequest): Observable<Token>
    signIn({ body }: SignInRequest, opts?: OperationOpts): Observable<RawAjaxResponse<Token>>
    signIn({ body }: SignInRequest, opts?: OperationOpts): Observable<Token | RawAjaxResponse<Token>> {
        throwIfNullOrUndefined(body, 'body', 'signIn');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<Token>({
            url: '/api/auth',
            method: 'POST',
            headers,
            body: body,
        }, opts?.responseOpts);
    };

}
