// tslint:disable
/**
 * of Turnkey API
 * Documentation for Turnkey API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, HttpQuery, throwIfNullOrUndefined, encodeURI, OperationOpts, RawAjaxResponse } from '../runtime';
import {
    GenericError,
    RoommateDto,
    ValidationError,
} from '../models';

export interface CreateRoommateRequest {
    body: RoommateDto;
}

export interface DeleteRoommateRequest {
    id: string;
}

export interface GetRoommateRequest {
    id: string;
}

export interface GetRoommatesByUserIdRequest {
    userId: string;
}

export interface UpdateRoommateRequest {
    id: string;
    body: RoommateDto;
}

/**
 * no description
 */
export class RoommateApi extends BaseAPI {

    /**
     * create a new roommate
     */
    createRoommate({ body }: CreateRoommateRequest): Observable<void>
    createRoommate({ body }: CreateRoommateRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>>
    createRoommate({ body }: CreateRoommateRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>> {
        throwIfNullOrUndefined(body, 'body', 'createRoommate');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>({
            url: '/api/roommate',
            method: 'POST',
            headers,
            body: body,
        }, opts?.responseOpts);
    };

    /**
     * delete a roommate
     */
    deleteRoommate({ id }: DeleteRoommateRequest): Observable<void>
    deleteRoommate({ id }: DeleteRoommateRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>>
    deleteRoommate({ id }: DeleteRoommateRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>> {
        throwIfNullOrUndefined(id, 'id', 'deleteRoommate');

        return this.request<void>({
            url: '/api/roommate/{id}'.replace('{id}', encodeURI(id)),
            method: 'DELETE',
        }, opts?.responseOpts);
    };

    /**
     * return a roommate
     */
    getRoommate({ id }: GetRoommateRequest): Observable<RoommateDto>
    getRoommate({ id }: GetRoommateRequest, opts?: OperationOpts): Observable<RawAjaxResponse<RoommateDto>>
    getRoommate({ id }: GetRoommateRequest, opts?: OperationOpts): Observable<RoommateDto | RawAjaxResponse<RoommateDto>> {
        throwIfNullOrUndefined(id, 'id', 'getRoommate');

        return this.request<RoommateDto>({
            url: '/api/roommate/{id}'.replace('{id}', encodeURI(id)),
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * return all roommates for a user
     */
    getRoommatesByUserId({ userId }: GetRoommatesByUserIdRequest): Observable<Array<RoommateDto>>
    getRoommatesByUserId({ userId }: GetRoommatesByUserIdRequest, opts?: OperationOpts): Observable<RawAjaxResponse<Array<RoommateDto>>>
    getRoommatesByUserId({ userId }: GetRoommatesByUserIdRequest, opts?: OperationOpts): Observable<Array<RoommateDto> | RawAjaxResponse<Array<RoommateDto>>> {
        throwIfNullOrUndefined(userId, 'userId', 'getRoommatesByUserId');

        const query: HttpQuery = { // required parameters are used directly since they are already checked by throwIfNullOrUndefined
            'userId': userId,
        };

        return this.request<Array<RoommateDto>>({
            url: '/api/roommate',
            method: 'GET',
            query,
        }, opts?.responseOpts);
    };

    /**
     * update a roommate
     */
    updateRoommate({ id, body }: UpdateRoommateRequest): Observable<void>
    updateRoommate({ id, body }: UpdateRoommateRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>>
    updateRoommate({ id, body }: UpdateRoommateRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>> {
        throwIfNullOrUndefined(id, 'id', 'updateRoommate');
        throwIfNullOrUndefined(body, 'body', 'updateRoommate');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>({
            url: '/api/roommate/{id}'.replace('{id}', encodeURI(id)),
            method: 'PUT',
            headers,
            body: body,
        }, opts?.responseOpts);
    };

}
