// tslint:disable
/**
 * of Turnkey API
 * Documentation for Turnkey API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, HttpQuery, throwIfNullOrUndefined, OperationOpts, RawAjaxResponse } from '../runtime';
import {
    ShortUrlDto,
} from '../models';

export interface GetShortUrlRequest {
    url: string;
    token: string;
}

/**
 * no description
 */
export class ShorturlApi extends BaseAPI {

    /**
     * return a bitly short url
     */
    getShortUrl({ url, token }: GetShortUrlRequest): Observable<ShortUrlDto>
    getShortUrl({ url, token }: GetShortUrlRequest, opts?: OperationOpts): Observable<RawAjaxResponse<ShortUrlDto>>
    getShortUrl({ url, token }: GetShortUrlRequest, opts?: OperationOpts): Observable<ShortUrlDto | RawAjaxResponse<ShortUrlDto>> {
        throwIfNullOrUndefined(url, 'url', 'getShortUrl');
        throwIfNullOrUndefined(token, 'token', 'getShortUrl');

        const headers: HttpHeaders = {
            ...(token != null ? { 'Token': String(token) } : undefined),
        };

        const query: HttpQuery = { // required parameters are used directly since they are already checked by throwIfNullOrUndefined
            'url': url,
        };

        return this.request<ShortUrlDto>({
            url: '/v1/shorturl',
            method: 'GET',
            headers,
            query,
        }, opts?.responseOpts);
    };

}
