// tslint:disable
/**
 * of Turnkey API
 * Documentation for Turnkey API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined, encodeURI, OperationOpts, RawAjaxResponse } from '../runtime';
import {
    UserDto,
} from '../models';

export interface ActivateUserRequest {
    id: string;
    token: string;
}

export interface DeleteUserRequest {
    id: string;
    token: string;
}

export interface GetUserRequest {
    id: string;
    token: string;
}

export interface UpdateUserRequest {
    id: string;
    token: string;
    body: UserDto;
}

/**
 * no description
 */
export class UserApi extends BaseAPI {

    /**
     * activate a user
     */
    activateUser({ id, token }: ActivateUserRequest): Observable<void>
    activateUser({ id, token }: ActivateUserRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>>
    activateUser({ id, token }: ActivateUserRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>> {
        throwIfNullOrUndefined(id, 'id', 'activateUser');
        throwIfNullOrUndefined(token, 'token', 'activateUser');

        const headers: HttpHeaders = {
            ...(token != null ? { 'Token': String(token) } : undefined),
        };

        return this.request<void>({
            url: '/v1/user/{id}/activate'.replace('{id}', encodeURI(id)),
            method: 'POST',
            headers,
        }, opts?.responseOpts);
    };

    /**
     * delete a user
     */
    deleteUser({ id, token }: DeleteUserRequest): Observable<void>
    deleteUser({ id, token }: DeleteUserRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>>
    deleteUser({ id, token }: DeleteUserRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>> {
        throwIfNullOrUndefined(id, 'id', 'deleteUser');
        throwIfNullOrUndefined(token, 'token', 'deleteUser');

        const headers: HttpHeaders = {
            ...(token != null ? { 'Token': String(token) } : undefined),
        };

        return this.request<void>({
            url: '/v1/user/{id}'.replace('{id}', encodeURI(id)),
            method: 'DELETE',
            headers,
        }, opts?.responseOpts);
    };

    /**
     * return a user
     */
    getUser({ id, token }: GetUserRequest): Observable<UserDto>
    getUser({ id, token }: GetUserRequest, opts?: OperationOpts): Observable<RawAjaxResponse<UserDto>>
    getUser({ id, token }: GetUserRequest, opts?: OperationOpts): Observable<UserDto | RawAjaxResponse<UserDto>> {
        throwIfNullOrUndefined(id, 'id', 'getUser');
        throwIfNullOrUndefined(token, 'token', 'getUser');

        const headers: HttpHeaders = {
            ...(token != null ? { 'Token': String(token) } : undefined),
        };

        return this.request<UserDto>({
            url: '/v1/user/{id}'.replace('{id}', encodeURI(id)),
            method: 'GET',
            headers,
        }, opts?.responseOpts);
    };

    /**
     * update a user
     */
    updateUser({ id, token, body }: UpdateUserRequest): Observable<void>
    updateUser({ id, token, body }: UpdateUserRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>>
    updateUser({ id, token, body }: UpdateUserRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>> {
        throwIfNullOrUndefined(id, 'id', 'updateUser');
        throwIfNullOrUndefined(token, 'token', 'updateUser');
        throwIfNullOrUndefined(body, 'body', 'updateUser');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
            ...(token != null ? { 'Token': String(token) } : undefined),
        };

        return this.request<void>({
            url: '/v1/user/{id}'.replace('{id}', encodeURI(id)),
            method: 'PUT',
            headers,
            body: body,
        }, opts?.responseOpts);
    };

}
