// tslint:disable
/**
 * of Turnkey API
 * Documentation for Turnkey API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface EmploymentDto
 */
export interface EmploymentDto {
    /**
     * @type {string}
     * @memberof EmploymentDto
     */
    additionalDetails?: string;
    /**
     * @type {number}
     * @memberof EmploymentDto
     */
    annualSalary?: number;
    /**
     * @type {string}
     * @memberof EmploymentDto
     */
    createdOn?: string;
    /**
     * @type {string}
     * @memberof EmploymentDto
     */
    duration?: string;
    /**
     * @type {string}
     * @memberof EmploymentDto
     */
    employer?: string;
    /**
     * @type {string}
     * @memberof EmploymentDto
     */
    id?: string;
    /**
     * @type {string}
     * @memberof EmploymentDto
     */
    lastUpdated?: string;
    /**
     * @type {string}
     * @memberof EmploymentDto
     */
    occupation?: string;
    /**
     * @type {string}
     * @memberof EmploymentDto
     */
    rentAfforsability?: string;
    /**
     * @type {string}
     * @memberof EmploymentDto
     */
    userId?: string;
}
