// tslint:disable
/**
 * of Turnkey API
 * Documentation for Turnkey API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * PermissionDto PermissionDto PermissionDto PermissionDto PermissionDto PermissionDto permission dto
 * @export
 * @interface PermissionDto
 */
export interface PermissionDto {
    /**
     * created on
     * @type {string}
     * @memberof PermissionDto
     */
    createdOn?: string;
    /**
     * Id
     * @type {string}
     * @memberof PermissionDto
     */
    id?: string;
    /**
     * last updated
     * @type {string}
     * @memberof PermissionDto
     */
    lastUpdated?: string;
    /**
     * on user Id
     * @type {string}
     * @memberof PermissionDto
     */
    onUserId?: string;
    /**
     * PermissionType PermissionType PermissionType PermissionType PermissionType PermissionType permission type
     * @type {string}
     * @memberof PermissionDto
     */
    permission?: string;
    /**
     * user Id
     * @type {string}
     * @memberof PermissionDto
     */
    userId?: string;
}
