// tslint:disable
/**
 * of Turnkey API
 * Documentation for Turnkey API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface PetDto
 */
export interface PetDto {
    /**
     * @type {string}
     * @memberof PetDto
     */
    breed?: string;
    /**
     * @type {string}
     * @memberof PetDto
     */
    createdOn?: string;
    /**
     * @type {string}
     * @memberof PetDto
     */
    id?: string;
    /**
     * @type {string}
     * @memberof PetDto
     */
    lastUpdated?: string;
    /**
     * @type {string}
     * @memberof PetDto
     */
    petType?: string;
    /**
     * @type {string}
     * @memberof PetDto
     */
    sizeType?: string;
    /**
     * @type {string}
     * @memberof PetDto
     */
    userId?: string;
}
