// tslint:disable
/**
 * of Turnkey API
 * Documentation for Turnkey API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * ReferenceDto ReferenceDto ReferenceDto ReferenceDto ReferenceDto ReferenceDto reference dto
 * @export
 * @interface ReferenceDto
 */
export interface ReferenceDto {
    /**
     * additional details
     * @type {string}
     * @memberof ReferenceDto
     */
    additionalDetails?: string;
    /**
     * created on
     * @type {string}
     * @memberof ReferenceDto
     */
    createdOn?: string;
    /**
     * email
     * @type {string}
     * @memberof ReferenceDto
     */
    email?: string;
    /**
     * full name
     * @type {string}
     * @memberof ReferenceDto
     */
    fullName?: string;
    /**
     * Id
     * @type {string}
     * @memberof ReferenceDto
     */
    id?: string;
    /**
     * last updated
     * @type {string}
     * @memberof ReferenceDto
     */
    lastUpdated?: string;
    /**
     * phone number
     * @type {string}
     * @memberof ReferenceDto
     */
    phoneNumber?: string;
    /**
     * relationship
     * @type {string}
     * @memberof ReferenceDto
     */
    relationship?: string;
    /**
     * user Id
     * @type {string}
     * @memberof ReferenceDto
     */
    userId?: string;
}
