// tslint:disable
/**
 * of Turnkey API
 * Documentation for Turnkey API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * RegisterTokenDto RegisterTokenDto RegisterTokenDto RegisterTokenDto RegisterTokenDto RegisterTokenDto register token dto
 * @export
 * @interface RegisterTokenDto
 */
export interface RegisterTokenDto {
    /**
     * login Id
     * @type {string}
     * @memberof RegisterTokenDto
     */
    id?: string;
    /**
     * is new user
     * @type {boolean}
     * @memberof RegisterTokenDto
     */
    newUser?: boolean;
    /**
     * secret
     * @type {string}
     * @memberof RegisterTokenDto
     */
    secret?: string;
}
