// tslint:disable
/**
 * of Turnkey API
 * Documentation for Turnkey API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * RoommateDto RoommateDto RoommateDto RoommateDto RoommateDto RoommateDto roommate dto
 * @export
 * @interface RoommateDto
 */
export interface RoommateDto {
    /**
     * created on
     * @type {string}
     * @memberof RoommateDto
     */
    createdOn?: string;
    /**
     * email
     * @type {string}
     * @memberof RoommateDto
     */
    email?: string;
    /**
     * full name
     * @type {string}
     * @memberof RoommateDto
     */
    fullName?: string;
    /**
     * Id
     * @type {string}
     * @memberof RoommateDto
     */
    id?: string;
    /**
     * last updated
     * @type {string}
     * @memberof RoommateDto
     */
    lastUpdated?: string;
    /**
     * user Id
     * @type {string}
     * @memberof RoommateDto
     */
    userId?: string;
}
