// tslint:disable
/**
 * of Turnkey API
 * Documentation for Turnkey API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * ShortURLDto ShortURLDto short Url dto
 * @export
 * @interface ShortURLDto
 */
export interface ShortURLDto {
    /**
     * Url
     * @type {string}
     * @memberof ShortURLDto
     */
    url?: string;
}
