// tslint:disable
/**
 * of Turnkey API
 * Documentation for Turnkey API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * TokenDto TokenDto TokenDto TokenDto TokenDto TokenDto token dto
 * @export
 * @interface TokenDto
 */
export interface TokenDto {
    /**
     * Id
     * @type {string}
     * @memberof TokenDto
     */
    id?: string;
    /**
     * token
     * @type {string}
     * @memberof TokenDto
     */
    token?: string;
}
