// tslint:disable
/**
 * of Turnkey API
 * Documentation for Turnkey API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Token
 */
export interface Token {
    /**
     * @type {string}
     * @memberof Token
     */
    id?: string;
    /**
     * @type {string}
     * @memberof Token
     */
    token?: string;
}
