// tslint:disable
/**
 * of Turnkey API
 * Documentation for Turnkey API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UserDto
 */
export interface UserDto {
    /**
     * @type {string}
     * @memberof UserDto
     */
    additionalDetailsGeneral?: string;
    /**
     * @type {string}
     * @memberof UserDto
     */
    additionalDetailsLease?: string;
    /**
     * @type {string}
     * @memberof UserDto
     */
    bio?: string;
    /**
     * @type {string}
     * @memberof UserDto
     */
    createdOn?: string;
    /**
     * @type {boolean}
     * @memberof UserDto
     */
    creditCheck?: boolean;
    /**
     * @type {string}
     * @memberof UserDto
     */
    email?: string;
    /**
     * @type {boolean}
     * @memberof UserDto
     */
    evicted?: boolean;
    /**
     * @type {string}
     * @memberof UserDto
     */
    fullName?: string;
    /**
     * @type {string}
     * @memberof UserDto
     */
    id?: string;
    /**
     * @type {string}
     * @memberof UserDto
     */
    lastUpdated?: string;
    /**
     * @type {boolean}
     * @memberof UserDto
     */
    lawsuit?: boolean;
    /**
     * @type {string}
     * @memberof UserDto
     */
    loginId?: string;
    /**
     * @type {string}
     * @memberof UserDto
     */
    moveInDate?: string;
    /**
     * @type {string}
     * @memberof UserDto
     */
    moveOutDate?: string;
    /**
     * @type {string}
     * @memberof UserDto
     */
    movingReason?: string;
    /**
     * @type {string}
     * @memberof UserDto
     */
    nickname?: string;
    /**
     * @type {boolean}
     * @memberof UserDto
     */
    pets?: boolean;
    /**
     * @type {string}
     * @memberof UserDto
     */
    phoneNumber?: string;
    /**
     * @type {boolean}
     * @memberof UserDto
     */
    roommates?: boolean;
    /**
     * @type {boolean}
     * @memberof UserDto
     */
    securityDeposit?: boolean;
    /**
     * @type {boolean}
     * @memberof UserDto
     */
    sendNotifications?: boolean;
    /**
     * @type {boolean}
     * @memberof UserDto
     */
    smoker?: boolean;
    /**
     * @type {string}
     * @memberof UserDto
     */
    userStatusType?: string;
    /**
     * @type {string}
     * @memberof UserDto
     */
    userType?: string;
}
